### ISSUE TITLE
As a developer, enum types are used explicitly instead of implicit conversions from int

### ISSUE THREAD

**Issue by solarisstar** [solarisstar/rpgxEF#10]
e.g. weapon type has an enum, so weapon shouldn't be passed into a function as an int.

**Comment by solarisstar** [comment]
Might be worth abandoning this for now. The current organization of the project makes it very difficult to do this. e.g. ints are used instead of enum types in places because the enum type isn't included, and since header files aren't really widely used in this project, this would require a massive re-organization.

**Comment by MJLHThomassen** [comment]
Yea, lets just do this whenever we need a particular enum.
