### ISSUE TITLE
As a user, tab menu IDs are immediately correct

### ISSUE THREAD

**Issue by solarisstar** [solarisstar/rpgxEF#44]
I think this has to do with a null pointer somewhere. I generally know what I want to fix here but I'm not sure if it will work.

**Comment by MJLHThomassen** [comment]
I dont know if this would be a 2.4 or 2.5 feature depending on what exactly the error here is.

**Comment by solarisstar** [comment]
I'm pretty sure it's a local problem. Each client _HAS_ to have the entity number of all the other players since they can see that person and the assigned ID is systematic. (Lowest available id)

I've looked thorugh this code a bit and it looks like there's just an uninitialized field somewhere that's causing this to default to 0.

**Comment by solarisstar** [comment]
Even simpler. I'll submit a PR once I've had a chance to test this.
