### ISSUE TITLE
As a user, my RPG-X game uses a sensible amount of memory by default

### ISSUE THREAD

**Issue by solarisstar** [solarisstar/rpgxEF#50]
I'm thinking we should set com_hunkmegs to 512 by default. What do you think Martin?

**Comment by MJLHThomassen** [comment]
Agreed, 512 should be the default, thats the least you can expect from modern pc's.

**Comment by solarisstar** [comment]
https://github.com/solarisstar/rpgxEF/pull/52

**Comment by MJLHThomassen** [comment]
Closed in #52
