### ISSUE TITLE
As a developer, I would like to use Vagrant to manage a preconfigured development VM

### ISSUE THREAD

**Issue by MJLHThomassen** [solarisstar/rpgxEF#51]
Also include support for Visual Studio 2015 remote debugging with GDB pre-setup.

**Comment by solarisstar** [comment]
Would love to have VS debugging. We're getting onto some harder bugs that really need better tools than GDB.

**Comment by MJLHThomassen** [comment]
Alright, after reading many tutorials and doing it wrong 5 times i finally managed to set up a clean virtualbox vagrant base box for xubuntu 16.04 x64. You can find it at TLO/xenial64:

`vagrant init TLO/xenial64`
`vagrant up`

I'm going to continue with it this week, making a RPGXEFDev box based on this one with all development dependencies installed and RPG-X Standard Edition stripped down into it. Entire image should end up around the 2.5 Gb mark then, but its just a one time download basically. I'll keep you updated.

**Comment by MJLHThomassen** [comment]
Looking good so far. Will push this on Friday. I got 2 things working now:

-Debugging via Xming (slow and mouse handeling is an issue)
-Debugging while running RPG-X inside the VM. Faster and good mouse handeling for RPG-X, but need to open the VM display (doesn't have to be an issue) and need to disable VirtualBox Mouse Integration for the mouse to work properly. This causes you to press right-ctrl (or w/e youve configured as Virtualbox host key) if you want to leave the VM environment and go back to Windows. Not a big issue, and the performance it has over Xming is pretty large, so this is the best option.

**Comment by MJLHThomassen** [comment]
I think this is almost ready to go. I havn't had any time this week to look at it. Will try to PR this this evening.
