### ISSUE TITLE
As a user, the UI has been re-colored with the winning submission from the UI design contest

### ISSUE THREAD

**Issue by solarisstar** [solarisstar/rpgxEF#65]

**Comment by MJLHThomassen** [comment]
What about creating a file or CVARS for each (base)color and having the ability to set them yourself?

Also, what about being able to override colors for the transporter and turbolift menu by a map maker on a per map .pk3 base?

**Comment by solarisstar** [comment]
Making the colors modular poses a few difficulties but I did think about the same thing last night. 

The more freedom we give people in modular color schemes, the more complicated our code will be. Id like to keep it simple for now and we can come back to modularity in the future.

**Comment by MJLHThomassen** [comment]
It would be a little bit more complex, not much though. We should definately keep it in mind in the future. At any rate, we should give people the option to switch back to the old color scheme.

I suggest creating a single "colorscheme.h" file #defining all colors used in the UI. For example:

#define UI_MAIN_COLOR name of actual color here
#define UI_BUTTON COLOR name of actual color here
#define UI_BUTTON_HOVER_COLOR name of actual color here

Then use those colors. That way, we can also limit the UI "designers" in the competion to those 30 colors you mentioned in the post by definining which elements should all carry the same color.

**Comment by solarisstar** [comment]
Yeah that's a good middle-ground solution, but then we're limiting to a mapping from current colors to new colors. Who knows? Someone might come up with a better scheme.

**Comment by solarisstar** [comment]
lol no one ever submitted anything. Closing this
