### ISSUE TITLE
As a developer, I want Windows x64 binaries to build

### ISSUE THREAD

**Issue by MJLHThomassen** [solarisstar/rpgxEF#71]
For some reason, even on master, windows binaries don't build for me. 
Apparantly, it is missing the rpgxef.ico:

> WINDRES code/sys/win_resource.rc
> x86_64-w64-mingw32-windres: can't open icon file `misc/rpgxef.ico': No such file or directory
> Makefile:2500: recipe for target 'build/release-mingw32-x64/ded/win_resource.o' failed
> make[2]: **\* [build/release-mingw32-x64/ded/win_resource.o] Error 1
> make[2]: Leaving directory '/vagrant/RPGXEFSrc'
> Makefile:1183: recipe for target 'targets' failed
> make[1]: **\* [targets] Error 2
> make[1]: Leaving directory '/vagrant/RPGXEFSrc'
> Makefile:1176: recipe for target 'release' failed
> make: **\* [release] Error 2

**Comment by solarisstar** [comment]
I remember seeing this problem when trying to build in VS. If you're trying to build on Linux, running cross-make-mingw is working for me on develop and will create 32-bit dlls.

**Comment by MJLHThomassen** [comment]
Yes, 32-bits is working for me aswell. Probably something missing/worng with 64-bits only then...

**Comment by solarisstar** [comment]
I threw three hours at this and couldn't figure out why it wasn't working.

**Comment by MJLHThomassen** [comment]
Strange, lets leave it for the moment and get back to it later.

ioquake3 added the support for x64 building with mingw anyways, perhaps there is a hint to the problem in that repo.

**Comment by solarisstar** [comment]
It's definitely a linker issue. For some reason the linker can't see the symbols in libmad.a nor libmad.dll.a. I used nm to dump the symbols from those files and all the ones the linker says it can't find are in there.

**Comment by solarisstar** [comment]
It may have to do with all the macros in the mad.h header file. That, or we need a different compiled version of the 64-bit library.

**Comment by MJLHThomassen** [comment]
This seems to be working now so I'm closing this. No idea what was wrong, probably a configuration thing on my end.
