### ISSUE TITLE
Linux builds are version rpgxEF 2.1, not version 2.3 & cpu arch file names

### ISSUE THREAD

**Issue by kwadroke** [solarisstar/rpgxEF#80]
When building on Debian 8 (32bit and 64bit) the version shows up as 2.1 instead of 2.3.
I copied the .so files in build/release-linux-*/rpgxEF to the RPG-X2 directory. I also ran it with the command line parameters _+set vm_game 0 +set vm_ui 0 +set vm_cgame 0 +set fs_game RPG-X2_.

Either I'm missing some information or there's something going on in the build scripts. I tried this using 2.3.4b release and the develop git branch source code.

The renderer_opengl1_x86.so must also be copied/symlinked to renderer_opengl1_x86_64.so (for 64bit) or  renderer_opengl1_i386.so (for 32bit). I also copy the .so files in the rpgxEF folder with the same changes.

**Comment by MJLHThomassen** [comment]
We havn't had a look at generating correct version numbers yet. Its a #define somewhere and the latest version numbers have not been commited to the repo. My guess is that release builds have been manually given version numbers before they got published. This is not a major issue for now.

**Comment by kwadroke** [comment]
I've been using the make-i386.sh script and that could be causing the naming issues after looking at this again this morning.

I've seen other errors; dropping the connection due to maps, and some others.
Probably due to the incorrect version that I don't see from the Official release. I'll post those once I get them again.

**Comment by kwadroke** [comment]
Ok. I think I got this working right now. My fault. It now has the proper version (2.3.4). I was missing some dependencies, even though it compiled without errors (besides one which I'll open a new issue on - needs CC=c99 in the Makefile). I think it was also due to me using the make-i386.sh script to compile.
